### ISSUE TITLE
Problem when create app

### ISSUE THREAD

**Issue by alejandrodazal** [leonanluppi/generator-japs#1]
I'm trying to execute the command, but when starting out creating this error message and do not identify the reason

![image](https://cloud.githubusercontent.com/assets/729676/9841453/98a846ea-5a65-11e5-89cd-75684e4988c0.png)

![image](https://cloud.githubusercontent.com/assets/729676/9841462/d3fbf12e-5a65-11e5-84b8-e2ff9c4b86e0.png)

I hope I was clear.
First of all, Thanks

**Comment by leonanluppi** [comment]
@alejandrodazal bug fixed. Thanks you.

**Comment by alejandrodazal** [comment]
Hello i try but the error it's the same, what i can do?

**Comment by leonanluppi** [comment]
@alejandrodazal do you update your generator-japs package using 'npm update generator-japs'?
